[tools]
pre-commit = "latest"
python = "3.14"

[tasks.setup]
description = "Automatically initialize dependencies and pre-commit hooks"
run = [
    "uv sync",
    "pre-commit install",
    "pre-commit install-hooks"
]

[hooks]
enter = { task = "setup" }
