[project]
name = "phish-intel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Don Lee", email = "git@mrdonlee.addy.io" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
phish-intel = "phish_intel:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
